### ISSUE TITLE
Update list of mandatory attributes in EnergyInvoice schema

### ISSUE THREAD

**Issue by HemangCDR** [ConsumerDataStandardsAustralia/standards-staging#107]
**Description**
Update the list of mandatory attributes in EnergyInvoice schema with correct values as per [decision 198](https://github.com/ConsumerDataStandardsAustralia/standards/files/7439898/Decision.198.-.Candidate.Billing.Invoicing.End.Points.pdf)

**Comment by nils-work** [comment]
Closing as resolved by https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/3c860c5408781c637c169facaf3e36ddb96819ab.
