### ISSUE TITLE
Add HTTP Response Code prefix to error codes in API endpoint documentation

### ISSUE THREAD

**Issue by markverstege** [ConsumerDataStandardsAustralia/standards-staging#113]
**Description**
[Get Transaction Detail API](https://consumerdatastandardsaustralia.github.io/standards/index.html#get-transaction-detail) accidentally omits the HTTP status code for some of the error codes. 

Add the status code as a prefix for consistency with the other error code listings.

**Comment by nils-work** [comment]
This appears to have been resolved through [#493 Get Transaction Detail - Client Error documentation](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/493) as part of [v1.18.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.18.0.html#v1-18-0-release-notes).
