### ISSUE TITLE
Update text description of bulk balance for energy in endpoint version schedule

### ISSUE THREAD

**Issue by HemangCDR** [ConsumerDataStandardsAustralia/standards-staging#115]
**Description**
The text description of energy bulk balance API in [Energy endpoint version schedule ](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#energy-apis) needs to be changed from "Get Bulk Balances (Energy)" to "Get Bulk Balances for Energy" to align with standards

**Comment by dsbivan** [comment]
This change was incorporated into [release v1.16.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.0.html#v1-16-0-release-notes).
