### ISSUE TITLE
Change type of "page" and "page-size" in Energy APIs to PositiveInteger

### ISSUE THREAD

**Issue by HemangCDR** [ConsumerDataStandardsAustralia/standards-staging#116]
**Description**
Change type of "page" and "page-size" attribute in Energy APIs from number to PositiveInteger as number can be negative.  This change will also align it with Banking.

**Comment by dsbivan** [comment]
This change was incorporated into [release v1.16.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.0.html#v1-16-0-release-notes).
