### ISSUE TITLE
Suggestion to remove 'denotes' from 'Retirement Date' description 

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#129]
**Description**
Minor edit; suggest removing superfluous word, 'denotes', from 'Retirement Date' in:  https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#endpoint-version-schedule

![image](https://user-images.githubusercontent.com/94343290/154894757-76217f84-3044-4357-af6b-19587967663b.png)

**Related Work Items**
Where applicable please supply a list of related work items (using #issue format):
    - none

**Comment by nils-work** [comment]
Hi @elizabetharnold 
This should be resovled by [this change](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/586#issuecomment-1552318475).

**Comment by nils-work** [comment]
Resolved in v1.25.0
