### ISSUE TITLE
Increase visibility of Endpoint Version Schedule by adding link to End Point Versioning section

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#130]
**Description**
Add a link to the 'Endpoint Version Schedule' under the subheading 'End Point Versioning' in Versioning section shown in the first image below https://consumerdatastandardsaustralia.github.io/standards/#versioning.  

Suggested content:
A table view of endpoint versioning details, including method, Binding, Retirement, Introduction and Deprecation dates, is available here https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#endpoint-version-schedule.

<insert image to illustrate if possible, see second image below>

Image 1
![image](https://user-images.githubusercontent.com/94343290/154895281-1c7ef9a2-a445-4925-87d1-b1577ff655eb.png)

Image 2
![image](https://user-images.githubusercontent.com/94343290/154896305-e0e41aa4-b77c-4e32-b92c-eb9637432d77.png)

**Related Work Items**
Where applicable please supply a list of related work items (using #issue format):
    - none

**Comment by nils-work** [comment]
Closing as resolved through https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/143.
