### ISSUE TITLE
Update and standardise referencing to Normative References throughout

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#132]
**Description**
Normative standards are inconsistently referenced throughout the CDS.  The full suite of references needs to be consolidated and standardised.

**Related Work Items**
    - None

**Comment by nils-work** [comment]
Closing this issue as it was resolved in [v1.16.1](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.16.1.html#high-level-standards).
