### ISSUE TITLE
Capitalise 'BPAY' in CX Standards' Payee data cluster

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards-staging#135]
### Description
[CX Standards: Banking Language](https://consumerdatastandardsaustralia.github.io/standards/#banking-language): In the 'Payees' data cluster, change 'BPay' to 'BPAY'

### Related Work Items
None

**Comment by JamesMBligh** [comment]
Addressed in 1.16.1
