### ISSUE TITLE
Correct controlledLoad flag description

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#140]
**Description**
controlledLoad is a boolean but the description says to use Yes and No as values.

**Comment by JamesMBligh** [comment]
After review this needs to be a CR as the underlying field from AEMO isn't purely a flag.  In the case of a true state it contains meaningful data.  Would suggest the 'controlledLoad' field becomes:

'isControlledLoad' - optional boolean flag
'controlledLoadDescription' - conditional string describing the controlled load that is present if isControlledLoad is true

**Comment by JamesMBligh** [comment]
After referring to AEMO it appears that the underlying data is sparse so the intention was to have a boolean only.

Fixed in 1.16.1
