### ISSUE TITLE
Fix documentation defect for CDR Arrangement JWT method

### ISSUE THREAD

**Issue by markverstege** [ConsumerDataStandardsAustralia/standards-staging#155]
### Description
This issue addresses a documentation fix identified with the CDR Arrangement Revocation End Point. A Standards Maintenance issue has been raised for public visibility: [Fix documentation defect for CDR Arrangement JWT method](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/503).

This issue will correct the documentation bug and restore the correct documentation text for both JWT method and Form Parameter method.

**Comment by JamesMBligh** [comment]
Resolved in 1.17.0
