### ISSUE TITLE
Incorrect property name in EnergyServicePointListResponse definition

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataStandardsAustralia/standards-staging#192]
**Incorrect Required Property**
Relates to swagger-gen/api/cds_energy.json.
The EnergyServicePointListResponse has a required field of "me". This is obviously incorrect.

`            "EnergyServicePointListResponse": {
                "type": "object",
                "required": [
                    "data",
                    "links",
                    "me"
                ],
                "properties": {
                    "data": {
                        "type": "object",
                        "required": [
                            "servicePoints"
                        ],
                        "properties": {
                            "servicePoints": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/EnergyServicePoint"
                                }
                            }
                        }
                    },
                    "links": {
                        "$ref": "#/components/schemas/LinksPaginated"
                    },
                    "meta": {
                        "$ref": "#/components/schemas/MetaPaginated"
                    }
                }
            }`

**Comment by JamesMBligh** [comment]
Fixed in 1.20.0
