### ISSUE TITLE
Incorrect link to Endpoint Version Schedule in Standards

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#193]
In the Consumer Data Standards section [Endpoint Version Schedule](https://consumerdatastandardsaustralia.github.io/standards/#endpoint-version-schedule), the hyperlinked text 'here' navigates the user to Obligation Dates Schedule when selected.

![image](https://user-images.githubusercontent.com/94343290/170898316-8c2eaffd-1245-45cc-a1a3-793129d884c2.png)

Correct the link to navigate to https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#endpoint-version-schedule when selected.

**Comment by JamesMBligh** [comment]
Fixed in v1.22.1
