### ISSUE TITLE
Update CDR references in Introduction and Informative References sections

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#194]
**Description**
Update descriptions, references and links to CDR and partner agencies in the [Introduction](https://consumerdatastandardsaustralia.github.io/standards/#introduction) and [Informative references](https://consumerdatastandardsaustralia.github.io/standards/#informative-references) sections of the standards.

Content will be posted on this ticket when cleared.

**Related Work Items**
- none

**Comment by elizabetharnold** [comment]
[GitHub Staging Issue 194 Proposed changes to informative references.docx](https://github.com/ConsumerDataStandardsAustralia/standards-staging/files/9017303/GitHub.Staging.Issue.194.Proposed.changes.to.informative.references.docx)

@markverstege Changes are described in this document.

**Comment by nils-work** [comment]
Closing this issue as these changes were [incorporated into v1.18.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.18.0.html#high-level-standards).
