### ISSUE TITLE
Incorrect levelling of largeSecondary object

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards-staging#196]
**Description**
In the average response time metrics the secondary and largeSecondary objects are not shown at the same level in the markdown but they are in the examples and in the swagger.  This appears to be a generation bug

**Comment by nils-work** [comment]
For reference, the incorrect levelling of the `largeSecondary` property: 

![image](https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/60594671/ada6a2e7-91b5-4d3b-a4a4-221c51f1415f)

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
