### ISSUE TITLE
Update client registration non-normative examples to include energy sectors

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#197]
**Description**
The non-normative examples in the [Client Registration](https://consumerdatastandardsaustralia.github.io/standards/#client-registration) section are out of date. The encoded SSA is an old example and when decoded, does not map to the decoded example. As part of publishing GetSSA V3, we can bring this up to date including energy authorisation scopes.

**Comment by nils-work** [comment]
A fix for this issue has been staged for review - https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/9b9bea01513fc7931a40447d79b6c790e5c20c73#diff-744c2256b055bfde659f9288a88d6d4ca07bc6c7d684b66e7bc5cf02805973a7

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
