### ISSUE TITLE
Update documentation clarifying sort date for energy invoices

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#200]
**Description**
Update the description of [EnergyInvoice] in [EnergyInvoiceListResponse](https://consumerdatastandardsaustralia.github.io/standards/#tocSenergyinvoicelistresponse) to clarify the sorting is done by issueDate.

![image](https://user-images.githubusercontent.com/52149325/180142598-7c61d860-73d6-4e15-9754-d79a2196d8fb.png)

**Comment by JamesMBligh** [comment]
Included in v1.18.0
