### ISSUE TITLE
Link to CDR Test Documentation from CDS Menu 

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#220]
Include a link to **CDR Test Documentation** (https://consumerdatastandardsaustralia.github.io/standards-testing/latest/) at the bottom of the left menu in the Consumer Data Standards 
https://consumerdatastandardsaustralia.github.io/standards/#introduction

**Comment by JamesMBligh** [comment]
Included in v1.18.0
