### ISSUE TITLE
Standardise use of ResponseErrorListV2 for Energy APIs

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#226]
Energy APIs use ErrorListResponse whereas all other APIs use ResponseErrorListV2.  The schemas for these objects are the same however different names cause confusion, particularly in the CDR Test Documentation Test Cases and Assertions.

![image](https://user-images.githubusercontent.com/94343290/185552046-30b0b8e0-be32-4b89-8431-8c9e7532afb2.png)

**Comment by JamesMBligh** [comment]
Fixed in v1.22.1
