### ISSUE TITLE
Create an archived version of the current version at the time of publishing

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#230]
**Description**
The ACCC has requested the DSB create an archived version of the current version of the Consumer Data Standards at the time of publishing instead of when the next version is created.  This will provide a static link to specific content in each new version that is referenced in the Conformance Test Suite Test Plans and other reference materials.

**Related Work Items**
None

**Comment by nils-work** [comment]
Relates to -
https://www.cdr.gov.au/resources/guides/conformance-test-suite-version-history-and-guidance

**Comment by nils-work** [comment]
This change was incorporated through: 
https://github.com/ConsumerDataStandardsAustralia/standards-archives/commit/8485be3c7691d349d9bb0e625a83d850acb5d188
