### ISSUE TITLE
Correction to two links in Register APIs documentation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#234]
**Description**
These two links appear to have been broken in the transition from the Register repo -

![image](https://user-images.githubusercontent.com/60594671/196379940-53f0ca7a-b345-4766-ab36-65098e5df045.png)

https://consumerdatastandardsaustralia.github.io/standards/#register-apis

**Related Work Items**
1. Update links to the correct anchor (as per the [register archive](https://consumerdatastandardsaustralia.github.io/register/#consumer-data-right-cdr-register-apis)) which appears to be - https://consumerdatastandardsaustralia.github.io/standards/#participant-statuses

**Comment by JamesMBligh** [comment]
Resolved in v1.22.0
