### ISSUE TITLE
Missing font impacting load time

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#235]
**Description**
A font that appears to only be used for a few characters in the standards is currently unavailable, returning a 404 response that impacts the page load time.

![image](https://user-images.githubusercontent.com/60594671/196603764-a649cfd0-b7ff-4cbc-9d05-ce36ea4778dd.png)

**Related Work Items**
1. Review the requirement for the additional font (✔ character may suffice or replace with `Yes`, `No`) or correct the broken link/resource so it can be cached.

**Comment by JamesMBligh** [comment]
Fixed in v1.22.0
