### ISSUE TITLE
Review whether Code samples are useful

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#237]
**Description**
The `$.ajax` detail in the 'Code samples' section of the sidebar are unlikely to be useful for any non-CORS endpoints and include an incorrect sample base URI detail for all endpoints.

**Related Work Items**
Consider removing the 'Code sample' section from endpoints where it is not applicable, or remove entirely.

**Comment by JamesMBligh** [comment]
Resolved in v1.26.0
