### ISSUE TITLE
Energy APIs: meta object should not be mandatory

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#245]
The following Energy APIs have `meta` object incorrectly noted as mandatory:
- https://consumerdatastandardsaustralia.github.io/standards/#get-der-for-service-point
- https://consumerdatastandardsaustralia.github.io/standards/#get-energy-account-detail
- https://consumerdatastandardsaustralia.github.io/standards/#get-agreed-payment-schedule
- https://consumerdatastandardsaustralia.github.io/standards/#get-concessions
- https://consumerdatastandardsaustralia.github.io/standards/#get-balance-for-energy-account

This issue is raised to fix the defect by making `meta` optional

**Comment by JamesMBligh** [comment]
Fixed in v1.22.1
