### ISSUE TITLE
Apply consistent month name format

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#253]
**Description**
There is a mix of conventions for the month names in the [Normative References](https://consumerdatastandardsaustralia.github.io/standards/#normative-references) section. 

Some dates in the **Version** column use the 'mmm' format, others use 'mmmm' -
`Oct 2006`
`October 2008`

![image](https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/60594671/407ba7bb-2a93-458c-83e4-9d584d002683)

**Related Work Items**
Apply a consistent convention. The 'mmm' format appears less likely to wrap to two lines, but is different to the style in the [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations) and [Register Dependency Schedule](https://consumerdatastandardsaustralia.github.io/standards/#register-dependency-schedule) tables.

**Comment by JamesMBligh** [comment]
Resolved in v1.26.0
