### ISSUE TITLE
Get Energy Account Detail V2- Fix binding date

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#254]
**Description**
Binding date for Get Energy Account Detail V2 is incorrect (2022-04-14) on the [endpoint version schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#energy-apis)

**Related Work Items**
Fix the binding date for Get Energy Account Detail V2 on the endpoint version schedule to **2023-04-14**

**Comment by nils-work** [comment]
The four `TBC` values in the last two columns of rows 3-6 of the same table should also be replaced with `2022-09-13` (the [release date](https://consumerdatastandardsaustralia.github.io/standards/#change-log) of V1.19.0)

**Comment by JamesMBligh** [comment]
Fixed in v1.22.1

I don't think fixing past archives is appropriate.  They should stay as published
