### ISSUE TITLE
Maintenance of obligation date tables

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#255]
**Description**
Corrections to the two obligation date reference tables: 
- [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule)
- [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations)

**Related Work Items**

1. Changes to [Obligation Dates Schedule](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule), to align to [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations):

    1. The row `Y22 #3 31/08/2022` should state **# Obligations Assigned**: 3
    2. Insert a row `Legacy FDO 01/11/2022` before `Y22 #4` to state **# Obligations Assigned**: 1 ([i.e. Standard Error Codes](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations) `Data Holders MAY retire application-specific error codes`)
    3. The row `Y22 #4 15/11/2022` should state **# Obligations Assigned**: 3 (this excludes `Data Holders MAY implement the isSecondaryDataHolderError`, which becomes a MUST at Milestone `Y23 #2`)
    4. The row `Y23 #1 14/04/2023` should state **# Obligations Assigned**: 3
    5. The row `Y23 #2 08/05/2023` should be [changed to](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/506#issuecomment-1283644613) `15/05/2023` and state **# Obligations Assigned**: 1
    6. The row `Y23 #3 10/07/2023` should state **# Obligations Assigned**: 3
    7. The row `Y24 #1 11/03/2024` should state **# Obligations Assigned**: 2

2. Changes to [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations):
    1. Correct four instances of the typo `endopint`
    2. Sort the table by the **Applicable Date** column:
          1. `Registration Validation` (August 31st 2022) should follow `Get Payee Detail V1` (August 31st 2022)
          2. `Get Energy Accounts V1` and `Get Energy Account Detail V1` (November 15th 2022) should follow `Data Recipient CDR Arrangement Endpoint` (November 15th 2022)
          3. `Error Codes: Secondary Data Holder flag` (May 15th 2023) should follow the three items dated April 14th 2023
    4. Transfer any rows ~6 months past their **Applicable Date** to a new _'Past Obligation Dates'_ page for historical reference only.

**Comment by JamesMBligh** [comment]
Fixed in v1.22.1

I didn't create the past obligation dates as these can be seen in previous standards version.  It will just create another point of maintenance
