### ISSUE TITLE
Typos in archived Register API versions

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#256]
**Description**
There are typos in the blue 'aside' notes in the following Obsolete version pages, in the text:
`This version is will remain valid until a deprecation schedule is set.`

It should state: 
`This version will remain valid until a deprecation schedule is set.`

**Related Work Items**
Correct the text on the following pages:
1. [Get Data Holder Brands V1](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-data-holder-brands-v1.html#get-data-holder-brands-v1)
2. [Get Software Products Statuses V1](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-software-product-statuses-v1.html#get-software-products-statuses-v1)
3. [Get Data Recipient Statuses V1](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-data-recipient-statuses-v1.html#get-data-recipient-statuses-v1)
4. [Get Data Recipients V2](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-data-recipients-v2.html#get-data-recipients-v2)

**Comment by JamesMBligh** [comment]
Resolved in v1.26.0
