### ISSUE TITLE
Notice for the Binding Data Standard

### ISSUE THREAD

**Issue by DSB-RT** [ConsumerDataStandardsAustralia/standards-staging#257]
**Description:**
Update the '[Interpretation](https://consumerdatastandardsaustralia.github.io/standards/#interpretation)' section of the Consumer Data Standards to include the following text to appear below existing content.

"Some of these standards will be binding data standards under the Competition and Consumer (Consumer Data Right) Data Standards (No. 1) 2023. See that instrument [here](https://consumerdatastandards.gov.au/sites/consumerdatastandards.gov.au/files/2023-02/Competition%20and%20Consumer%20%28Consumer%20Data%20Right%29%20Data%20Standards%20%28No.%201%29%202023%20executed.pdf). In summary, provisions of these standards (as they exist from time to time) that impose obligations or prohibitions on CDR entities are binding data standards. Provisions included in these standards merely by way of guidance are not binding data standards."

This text must be copied verbatim.  If any changes are needed a legal review is required.

**Comment by JamesMBligh** [comment]
Added in v1.22.1
