### ISSUE TITLE
Get Accounts V1 link in FDO

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#270]
The **Get Accounts V1** link in the [Future Dated Obligations](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations) table goes to the wrong section (\#get-account-detail), it should point to [Get Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-accounts) (\#get-accounts)

**Comment by JamesMBligh** [comment]
Resolved in v1.26.0
