### ISSUE TITLE
Typos in Get Transactions For Account parameters

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#271]
**Description**
There are two typos in the following parameters of [Get Transactions For Account](https://consumerdatastandardsaustralia.github.io/standards/#get-transactions-for-account).

**Related Work Items**
Make the following edits to the descriptions for the `min-amount` and `max-amount` parameters.

Name | Description
-- | --
min-amount | Filter transactions to only transactions with amounts higher **than** or equal to ~~than~~ this amount
max-amount | Filter transactions to only transactions with amounts less than or equal to ~~than~~ this amount

**Comment by JamesMBligh** [comment]
Resolved in v1.26.0
