### ISSUE TITLE
Incorrect non-normative example

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/standards-staging#307]
**Description**
The value of `code_challenge_methods_supported ` in the non-normative example in the [Security Endpoints](https://consumerdatastandardsaustralia.github.io/standards/#security-endpoints) section needs to be an array rather than a string

**Comment by nils-work** [comment]
A fix for this issue has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/154471036d608aff965b582c4ce47f673c5b2148

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
