### ISSUE TITLE
Fix link to FAPI section reference

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#308]
**Description**
Link to section 8.6 of FAPI Advanced incorrectly references the old draft version.

**Related Work Items**
Change `[section 8.6](https://openid.net/specs/openid-financial-api-part-2.html#jws-algorithm-considerations)`

To be `[section 8.6](https://openid.net/specs/openid-financial-api-part-2-1_0.html#algorithm-considerations)`

**Comment by nils-work** [comment]
A fix for this has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/2d824cfd91728dacb63d26b65db902943e768745

**Comment by nils-work** [comment]
This change has been incorporated into version 1.27.0
