### ISSUE TITLE
Special characters around “effective” in cds_full

### ISSUE THREAD

**Issue by plambrechtsen** [ConsumerDataStandardsAustralia/standards-staging#32]
**Description**
The current cds_full has the open and close double quotes around “effective” in the specification and that is not properly converted in UTF-8 when viewing the YAML file.

This can be seen in the following files:

https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_full.json#L368
https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/docs/includes/swagger/cds_full.json#L481
https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/docs/includes/swagger/cds_full.yaml#L445

`
data holder will use the “effective” date/time which will be defined as
`

When the YAML file is viewed via a browser in the main site:

https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.yaml

It is displayed as:

`
data holder will use the â€œeffectiveâ€� date/time which will be defined as
`

Whereas it should have a standard single quote character for the input string, or no quotes around effective at all then there wouldn't be the UTF-8 conversion issue.

**Related Work Items**
Where applicable please supply a list of related work items (using #issue format):
None

**Comment by markverstege** [comment]
Hi @plambrechtsen thanks for this bug fix request. I have transferred it across to our public Standards Maintenance issue tracker: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/400

This will be addressed in the next release as a bug fix. In future, if you can raise new change requests on Standards Maintenance that will help us. Standards Maintenance is used for public consultation on changes whilst Standards Staging is used for internal issue tracking and draft publication of pre-release data standards.

Cheers!

**Comment by markverstege** [comment]
This issue has been staged for release in 1.11.1: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.1...maintenance/400
