### ISSUE TITLE
BankingPayee.type and BankingPayeeDetail.payeeUType

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataStandardsAustralia/standards-staging#328]
**Description**

Logically BankingPayee.type and BankingPayeeDetail.payeeUType will always have the same value.
This classifies as data duplication and should be fixed, or if they can indeed have different values this needs to be clarified in the technical standard.

**Comment by nils-work** [comment]
Hi @tom-schier 

I think BankingPayee.`type` and BankingPayeeDetail.`payeeUType` would often have similar values, e.g.

```
  "type": "DOMESTIC",
  "payeeUType": "domestic"
  "domestic": {
    ...
```
but there could also be cases where they differ. One example was mentioned in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/596#issuecomment-1668979456) related to a potential change to this schema.

That means these values could be valid - 
```
  "type": "DOMESTIC",
  "payeeUType": "international"
  "international": {
      ...
```
The key point is that the detail object being provided must match the `payeeUType`, but the `payeeUType` doesn't necessarily have to match the `type`.
