### ISSUE TITLE
Add tracking and usage of the Standards

### ISSUE THREAD

**Issue by CDR-Engagement-Stream** [ConsumerDataStandardsAustralia/standards-staging#329]
**Description**
Include the tracking and usage tracking on the Consumer Data Standards. 

**Related Work Items**
    - Remove existing tracking 
    - Add Fathom Analytics snippet to <header>

`<!-- Fathom - beautiful, simple website analytics --> <script src="https://cdn.usefathom.com/script.js" data-spa="auto" data-site="GWAEHCUX" defer></script>  <!-- / Fathom -->`

**Comment by nils-work** [comment]
[Staged](https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/26389f7b72ba9c71b4c5ee07818a8a0d2bb2ff2e)  and incorporated into v1.28.0
