### ISSUE TITLE
Defect in payload conventions section

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#37]
**Description**
In payload conventions an older statement relating to empty fields being acceptable for optional fields needs to be removed as it conflicts with the more specific optionality section.

See the **Optional fields** heading in:
https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions

**Comment by CDR-API-Stream** [comment]
This has been corrected for review in branch [defect/37](https://github.com/ConsumerDataStandardsAustralia/standards-staging/tree/defect/37).

**Comment by markverstege** [comment]
This change will be included in v1.10.0
