### ISSUE TITLE
Fix typo in Amending Authorisation Standards: Changing Attributes

### ISSUE THREAD

**Issue by elizabetharnold** [ConsumerDataStandardsAustralia/standards-staging#388]
**Description**
There is a typo in the [Changing Attributes](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-standards:~:text=selection%20of%20accounts.-,Changing%20Attributes,-Data%20Holders%20MUST) section of the CX Standards: Amending Authorisation Standards.

Change 

- attributed
to
- attribute

as shown.

![image](https://github.com/ConsumerDataStandardsAustralia/standards-staging/assets/94343290/65973be5-d386-40d9-b6c1-34fb838cc296)

This text only change is non-breaking.

**Related Work Items**
    - None

**Comment by nils-work** [comment]
This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/389/commits/b6d1ea755ab732a432ddb6c23e7a4efc40c083de
