### ISSUE TITLE
Clarify RateString description and examples

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#410]
**Description**
A small number of queries regarding the format of the **RateString** type suggests the description and examples could be improved.

**Related Work Items**
Change the current detail: 
Type | Description | Valid Examples
:-- | :-- | :--
RateString | A string representing a percentage (e.g. an interest rate). A rate of 100% would be represented by the value 1.0 and a rate of -100% by -1.0<br>- At least 1 and up to a total of 16 significant digits before decimal point<br>- Up to 16 digits following the decimal point<br>- No formatting, eg thousand separating commas | “0.05”`(=5%)`<br>“-0.05”`(=-5%)`<br>“12.3456789”`(=1234.56789%)`<br>“-99.123456789123”`(=9912.3456789123%)`

**To:**
Type | Description | Valid Examples
:-- | :-- | :--
RateString | A string representing a percentage (e.g., an interest rate **or ratio**). **For example,** a rate of 100% would be represented by the value `"1"` and a rate of -100% by `"-1"`<br>- At least 1 and up to a total of 16 significant digits before **a** decimal point<br>- Up to 16 digits following **a** decimal point **if required**<br>- No formatting, e.g., thousand separating commas. | <ul><li>`"0"` or `"0.0"`&nbsp;&nbsp;(0%)<li>`"1"` or `"1.0"`&nbsp;&nbsp;(100%)<li>`"-1.234567"`&nbsp;&nbsp;(-123.4567%)<li>`"-0.056"`&nbsp;&nbsp;(-5.6%)<li>`"0.03456789"`&nbsp;&nbsp;(3.456789%)<li>`"0.2"`&nbsp;&nbsp;(20%)<li>`"23.456"`&nbsp;&nbsp;(2345.6%)

Note: **Bold** and `code` words in the updated description indicate change/addition.

**Comment by ProductCloudCDR** [comment]
Looks good.  Just to clarify, this is intended to be purely a description change.  It isn't an actual change in the standard itself.  Is that correct?

**Comment by nils-work** [comment]
Hi @ProductCloudCDR 

Yes, it's intended to be a description change, in response to questions such as -
- _Is "0" acceptable or does the RateString format require "0.0"?_

The update is an attempt to clarify that `0` and `0.0` or `1` and `1.0` could be assumed to be equivalent and that a decimal may only be present if required, which may not have been clear in the previous documentation. 
Participants would be advised to confirm whether this clarification would impact their systems.

**Comment by nils-work** [comment]
This has been [staged](https://github.com/ConsumerDataStandardsAustralia/standards-staging/pull/420/files) for review.

**Comment by nils-work** [comment]
Incorporated into Standards v1.32.0
