### ISSUE TITLE
Fix spelling, grammar and punctuation

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-staging#431]
Continuing from [#527 - Fix spelling, grammar and punctuation errors across the API specification](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/527), key remaining documentation changes appear to be: 
- Standardise `end point` to `endpoint` and `end points` to `endpoints`,
- Add a full-stop to the end of description sentences,
- Correct spelling/typos as necessary,
- White space (double spaces).

**Comment by nils-work** [comment]
This change extends to the following documentation corrections: 

1. Removed redundant blank lines and white space in source files.
2. Replaced double spaces in source files with single spaces.
3. Added spaces in some source files (mainly tables) for editing consistency.
4. Centre-aligned some table columns for clarity.
5. Updated field (_italic_) and value (`code`) styling in all sections.
6. Changed 'NA' to 'N/A'.
7. Added full-stops to most sentences.
8. Replaced curly quotes with straight quotes for simplicity and consistency.
9. Changed 'eg' to 'e.g.,', 'ie' to 'i.e.' and 'etc...' to 'etc.'.
10. Corrected typos and grammar throughout.
11. Changed 200 'Success' description in some specs to 'Successful response' for consistency across documentation only.
12. Integrated 'Version notes' detail (applicable to two Energy endpoints) into existing version number table.
13. Formatted all JSON source spec files for editing consistency.
14. Changed 'end point' and 'end-point' to 'endpoint'.
15. Clarified conditional field descriptions in CommonSimpleAddress in Banking specs to align to other specs. Requirement is unaffected.
16. Made Standards version number bold.
17. Tidied formatting of Non-normative Examples.
18. Clarified formatting in the URN Structure table.
19. Change 'TLS-MA' and 'mTLS' to 'MTLS' for consistency with normative reference link.
20. Removed two redundant source files.
21. Changed `</br>` and `<br/>` tags to `<br>`.
22. Changed 'True' and 'False' for Booleans in field descriptions to `true` and `false`.
23. Updated non-normative example value for _startInterval_ and _endInterval_ value in Energy _readQualities_ structure.
24. Removed redundant text in Energy endpoint property description - "_(may not be the best way to explain it but it is essentially a ‘subscription’ or telco style product_".
25. Corrected typo in description referring to _hasCentralProtectionAndControl_ to _hasCentralProtectionControl_.
26. Wrapped or unwrapped long documentation lines for improved clarity in different sections.
27. Added padding to the end of the release notes and changelog.

**Comment by perlboy** [comment]
Consistent formatting is great but according to _what_ stylesheet? Suggest implementing a pre-commit hook using the off the shelf JSON formatter from here https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#pretty-format-json . 

As someone who has had the tab vs. spaces fight numerous times and whose style preference conflicts with my own development team I can _absolutely guarantee_ individuals formatting JSON files without a repository defined expectation promises only to create mass pointless diffs as formatters collide.
