### ISSUE TITLE
Maintenance Iteration 21 - typos and formatting

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#435]
This change request has been created to simplify the raising of typos and formatting changes in Maintenance Iteration 21. 

If the change has a real impact on readability and clarity it should be posted on [Maintenance Iteration 21 Holistic Feedback](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/663) for the community's visibility.

The Decision Proposal for Maintenance Iteration 21 is https://github.com/ConsumerDataStandardsAustralia/standards/issues/356.

**Comment by nils-work** [comment]
Suggest tidying the formatting across the different OAS for consistency.
Improving the formatting will assist with clarity when editing and should cause no impact to the output specs or the Standards.

**Comment by nils-work** [comment]
There are five absolute links to anchors in the main Standards page that could be made relative to avoid page reloads in certain circumstances (e.g. when the current URL contains `/index.html#...`). All other intra-page links appear to be relative and always navigate immediately.
- 'CORS' link x 3
  - In the text "This endpoint does not require [CORS](https://consumerdatastandardsaustralia.github.io/standards/#cors)."
- 'Self-Signed JWT Client Authentication'
  - In the text "The cdr_arrangement_jwt SHOULD include all parameters in accordance with Data Holders calling Data Recipients using [Self-Signed JWT Client Authentication](https://consumerdatastandardsaustralia.github.io/standards/#self-signed-jwt-client-authentication)"
- 'minimum version' link in _x-min-v_ description of [Get Data Holder Statuses](https://consumerdatastandardsaustralia.github.io/standards/#cdr-participant-discovery-api_get-data-holder-statuses)

Updating common template links from `../index.html` to just `../` may also reduce instances of this.
