### ISSUE TITLE
Fix minor errors in CX accessiblity standards

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/standards-staging#51]
### Description
**Accessibility:** Content distinction - Remove duplicated sentence

**Accessibility:** Pointer interactions - Fix WCAG 2.5 hyperlink to: https://www.w3.org/WAI/WCAG21/Understanding/input-modalities

### Related Work Items
Published on maintenance here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/398

**Comment by markverstege** [comment]
This has been fixed in branch maintenance/398 for inclusion in release 1.11.1
