### ISSUE TITLE
Documentation Navigation Bar/Pane: Reinstate Banking APIs > Schemas subheadings

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/standards-staging#64]
### Hypothesis
Reinstate the subheadings within the Banking APIs > Schema heading in the navigation bar/pane

### Description
In the CDR Implementation Call on 21/10/21 James Bligh presented the staged CDS documentation site with the Banking APIs > Schemas heading in the navigation bar with no children. When questioned he explained that there had been comments suggesting that they not be included as 'most people' just used the browser Find in Page function. Like myself, I'm sure a lot of people use the navigation bar in addition to the Find function, so there does not appear to be a reason to remove the schema name (sub-headings) from the navigation bar. And if there's an argument that there are so many that it requires more scrolling in the navigation bar then I'd suggest it's better than scrolling through the document itself, which is the whole purpose of a navigation bar. One could also suggest that the navigation bar doesn't 'follow' the position in the document page or that it shouldn't automatically expand folders (requiring + and - features), but I'm sure that's not trivial (or possible) in Slate documentation.

### Available Options
1. Retain existing hiding of Banking APIs > Schema subheadings in documentation navigation bar
2. Revert to inclusion of Banking APIs > Schema subheadings in documentation navigation bar

**Comment by JamesMBligh** [comment]
We removed it because the, once expanded, the TOC items seemed infeasibly long and that would cause usability issues.  If the change actually has a net negative we will reinstate the TOC entries

**Comment by JamesMBligh** [comment]
This change has been incorporated into the published standards and deployed

**Comment by anzbankau** [comment]
Thanks for the quick action on this James. I can see from the result that it wasn't just a matter of reverting to the previous TOC because the change was combined with the merging of the Banking and Energy documentation, requiring the schemas to be pushed to the third level in the hierarchy. I'm not sure if there is a limitation in the depth of the TOC, but the schema sub-headings under Banking > Schemas and Energy > Schemas are listed at the same level as their Schema heading (i.e. at level 2) rather than as sub-headings of Schemas (i.e. level 3). Maybe that's why there was a concern that the TOC was considered to be too long - because the Schema heading didn't hide the schema items. If the schema headings could be pushed down to level 3 under the Schema headings in Banking and Energy the TOC would better reflect the structure. 

Going to a third level of indentation may require the TOC pane to be widened slightly. I know this can be a concern for smaller resolutions, but it looks like the code examples pane can be dynamically hidden rather than the current behaviour where the code examples pane takes precedence over the documentation. This also makes it unusable when zoomed for presentations.
