### ISSUE TITLE
Remove redundant comma from energy json OAS3

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#68]
**Description**
Energy OAS3 JSON line 128 has an erroneous comma which causes schema validation issues

**Related Work Items**
Remove the comma and validate the schema is OAS3 compliant

**Comment by nils-work** [comment]
This has been resolved as per: https://github.com/ConsumerDataStandardsAustralia/standards-staging/commit/38b90e03b61cf4614b6dae73a19d4fd94ee19873
