### ISSUE TITLE
Collapsible schema menus

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-staging#69]
### Description
Add collapsible schema lists

### Available Options
The schema lists are large and make quick sidebar navigation difficult. However they are useful for quick and easy searching. Add a solution that allows the schema list to be collapsed/expanded

**Comment by nils-work** [comment]
Closing this issue as it was resolved in [v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#high-level-standards).
