### ISSUE TITLE
Widdershins Endpoint Version text of undefined presented when endpoint version is not supported

### ISSUE THREAD

**Issue by dsbivan** [ConsumerDataStandardsAustralia/standards-staging#76]
**Description**
![image](https://user-images.githubusercontent.com/51106269/143985581-46a36ce8-bf72-4a63-a898-00a209ec41dc.png)

It is more meaningful to explicitly state that versioning is not supported for this endpoint.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0]
