### ISSUE TITLE
Register BaseUri value is incorrectly hard-coded

### ISSUE THREAD

**Issue by dsbivan** [ConsumerDataStandardsAustralia/standards-staging#87]
**Description**
In the Register API definitions, prior to the move to the CDS, the register APIs had a base URI defined as `<register-base-url>`

During the transition to the CDS, this was incorrectly defined as `register.cdr.gov.au`

The BaseUri needs to be used rather than an actual domain as the endpoints can be exposed in production, in the CTS, and in mock implementations. This value needs to remain generic.

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0]
